-- ==============================================================================
-- Velora Accessories - Supabase Database Schema
-- Run this in your Supabase Project -> SQL Editor -> Run
-- ==============================================================================

-- 1. Create the products table
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  price NUMERIC NOT NULL,
  available BOOLEAN DEFAULT true,
  image TEXT,
  tag TEXT,
  description TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- 3. Create Policies for Public Access (Read & Write for Boutique Management)
DROP POLICY IF EXISTS "Allow public read access" ON public.products;
CREATE POLICY "Allow public read access" ON public.products
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert" ON public.products;
CREATE POLICY "Allow public insert" ON public.products
  FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update" ON public.products;
CREATE POLICY "Allow public update" ON public.products
  FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Allow public delete" ON public.products;
CREATE POLICY "Allow public delete" ON public.products
  FOR DELETE USING (true);

-- 4. Enable Real-Time replication on products table
ALTER PUBLICATION supabase_realtime ADD TABLE public.products;

-- 5. Seed Initial Curated Boutique Products
INSERT INTO public.products (name, category, price, available, image, tag, description)
VALUES 
  (
    'Geometric Gold Hoop Earrings',
    'Earrings',
    2500,
    true,
    'https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&auto=format&fit=crop&q=80',
    'Best Seller',
    'Modern minimalist square-arch hoop earrings in 18K gold finish. Lightweight, hypoallergenic, and designed as the finishing touch to your everyday look.'
  ),
  (
    'Knotted Heart Gold Necklace',
    'Necklaces',
    3500,
    true,
    'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&auto=format&fit=crop&q=80',
    'Trending',
    'Sculptural open-heart pendant with a seamless knot detail on a fluid gold snake chain. 18K gold plated tarnish-resistant finish.'
  ),
  (
    'Layered Chain & Marble Charm Bracelet',
    'Bracelets',
    2800,
    true,
    'https://images.unsplash.com/photo-1611591477287-a128e469d76c?w=800&auto=format&fit=crop&q=80',
    'New',
    'Delicate multi-layered gold link chains paired with an artisan white marble round charm. Adjustable clasp for all wrist sizes.'
  ),
  (
    'Black Clover Motif Gold Bangle Set',
    'Bracelets',
    4200,
    true,
    'https://images.unsplash.com/photo-1602751584552-8ba73aad10e1?w=800&auto=format&fit=crop&q=80',
    'Exclusive',
    'Iconic four-leaf clover motif bangle set with rich black enamel inlays on 18K gold plated titanium steel. Timeless Parisian elegance.'
  ),
  (
    'Black Onyx Rectangle Pendant Necklace',
    'Necklaces',
    3200,
    false,
    'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&auto=format&fit=crop&q=80',
    'Pre-Order',
    'Sleek rectangular polished black onyx stone framed in lustrous gold snake chain. Perfect for layering or wearing solo.'
  ),
  (
    'Ruched Croissant Cloud Bag - Ivory White',
    'Bags',
    6500,
    true,
    'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800&auto=format&fit=crop&q=80',
    'Lifestyle',
    'Soft buttery vegan leather ruched dumpling shoulder bag with scrunchie top handle. Chic minimalist statement piece.'
  ),
  (
    'Pearl Blossom Velvet Hair Pin & Clip',
    'Hair Accessories',
    1800,
    true,
    'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=800&auto=format&fit=crop&q=80',
    'Popular',
    'Artisan freshwater pearl cluster hair clip with delicate gold hardware. Secure grip for elevated hairstyles.'
  ),
  (
    'Minimalist Twisted Dome Ring Trio',
    'Rings',
    2900,
    false,
    'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=800&auto=format&fit=crop&q=80',
    'Pre-Order',
    'Set of three stacking rings featuring a twisted croissant band, smooth dome ring, and sleek micro-band in 18K gold vermeil.'
  )
ON CONFLICT DO NOTHING;
